### ISSUE TITLE
1.0.1 broken

### ISSUE THREAD

**Issue by JesusLopTem** [sinergise/qgis_sentinel_hub#6]
When I try to install 1.0.1 version I got this message: 
The plugin is broken. Python says:
No module named enum

QGIS 2.18.15 under OS X El Capitan 10.11.6.

**Comment by derecd** [comment]
Great plugin. Same issue as above on a Win10 machine
Fresh install QGIS 2.18.16 (QGIS code revision | d473c3071a)
Using SentinelHub plugin from the QGIS repo (Available version: 1.0.1 (in QGIS Official Plugin Repository))

Thanks

**Comment by AleksMat** [comment]
Hi,

this problem is happening because the Python version your QGIS is using does not have a package `enum` installed. A few years ago the `enum` package was included to the standard Python 2.7 library however eariler versions of Python 2.7 do not have it by default.

In order to make the plugin work try to install `enum` Python package. The solution using pip is written [here](https://stackoverflow.com/questions/26828206/importerror-no-module-named-enum).

In OS X the QGIS should use the same Python distribution as the operating system. However in Windows it uses its own distribution. Therefore please check [this post](https://gis.stackexchange.com/questions/141320/how-to-install-3rd-party-python-libraries-for-qgis-on-windows) and [these instructions](https://www.lutraconsulting.co.uk/blog/2016/03/02/installing-third-party-python-modules-in-qgis-windows/) about installing new packages to QGIS's Python distribution.

If you will try this let us know if it worked.

I have also decided to remove `enum` dependancies from the plugin as it is clearly causing too much problems in QGIS 2.x. The new version will be released today.

**Comment by nietosac** [comment]
Testing out QGIS 3.0 on Windows 7 
Using SentinelHub plugin from the QGIS repo (Available version: 1.0.2 (in QGIS Official Plugin Repository))
Icon and panel are shown, but python error of "IndexError: list index out of range."

**Comment by AleksMat** [comment]
Ah this one is totally my fault, I missed a bug. I have just released version 1.0.3 where this is fixed and plugin should work.

Thanks for letting us know about the error.
